title = "Siziksu's Blog"
baseURL = "https://siziksu.github.io/blog/"
languageCode = "en-us"
publishDir = "docs"
paginate = 6
pygmentsCodeFences=true

[params]
  description = "Blog about Linux, Kotlin, Android, Git and more"
  copyright = "© 2019"

  cover = "images/architecture-bridge-buildings-2129814.jpg"
  customCSS = ["css/main.css", 
                "css/nav.css", 
                "css/page.css", 
                "css/pagination.css", 
                "css/single_page.css", 
                "css/single_post.css", 
                "css/list.css", 
                "css/terms.css", 
                "css/taxonomy.css", 
                "css/post_card.css"]

  githubName = "Siziksu"
  linkedinName = "esteban-latre"

  author = "Esteban Latre"
  authorAvatar = "images/profile_picture.png"
  authorLocation = "Barcelona, Catalunya"
  authorDescription = "Android Developer. Kotlin and Linux enthusiast."

  randomImages = 4

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 199

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 198
  